import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { websitesApi, scansApi } from '../api/resources';
import { useAuth } from '../context/AuthContext';
import Icon from '../components/Icon';
import SeverityBadge from '../components/SeverityBadge';

const EMPTY={name:'',url:'',environment:'Production',scanFrequency:'Manual',scanType:'Full'};
export default function WebsitesPage(){
 const {user}=useAuth(); const qc=useQueryClient(); const [open,setOpen]=useState(false); const [form,setForm]=useState(EMPTY); const [busy,setBusy]=useState(null); const [error,setError]=useState('');
 const {data:websites=[],isLoading,isError}=useQuery({queryKey:['websites'],queryFn:websitesApi.list});
 const canWrite=['Administrator','Security Analyst'].includes(user?.role);
 const create=useMutation({mutationFn:websitesApi.create,onSuccess:()=>{qc.invalidateQueries({queryKey:['websites']});setForm(EMPTY);setOpen(false);setError('')},onError:e=>setError(e.response?.data?.message||'Could not add website.')});
 const status=useMutation({mutationFn:({id,status})=>websitesApi.setStatus(id,status),onSuccess:()=>qc.invalidateQueries({queryKey:['websites']})});
 const remove=useMutation({mutationFn:websitesApi.remove,onSuccess:()=>qc.invalidateQueries({queryKey:['websites']})});
 async function scan(id){setBusy(id);setError('');try{const result=await scansApi.start(id);await Promise.all([qc.invalidateQueries({queryKey:['websites']}),qc.invalidateQueries({queryKey:['dashboard']}),qc.invalidateQueries({queryKey:['scans']})]); if(result.scan?.id) window.location.href=`/scans/${result.scan.id}`;}catch(e){setError(e.response?.data?.message||'Scan could not be completed.')}finally{setBusy(null)}}
 return <div>
  <div className="page-head"><div><h2 className="page-title">Websites</h2><p className="page-desc">Manage targets, run audits and review the latest security posture.</p></div>{canWrite&&<button className="btn btn-primary" onClick={()=>{setOpen(v=>!v);setError('')}}><Icon name={open?'x':'plus'} size={15}/>{open?'Close':'Add website'}</button>}</div>
  {error&&<div className="alert alert-error">{error}</div>}
  {open&&<form className="card form-grid" onSubmit={e=>{e.preventDefault();create.mutate(form)}}><Field label="Website name"><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="My production website" required/></Field><Field label="Website URL"><input className="input" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://example.com" required/></Field><Field label="Environment"><select className="input" value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}><option>Production</option><option>Staging</option><option>Development</option></select></Field><Field label="Scan frequency"><select className="input" value={form.scanFrequency} onChange={e=>setForm({...form,scanFrequency:e.target.value})}><option>Manual</option><option>Daily</option><option>Weekly</option><option>Monthly</option></select></Field><Field label="Scan type"><select className="input" value={form.scanType} onChange={e=>setForm({...form,scanType:e.target.value})}><option>Full</option><option>Headers Only</option><option>SSL Only</option><option>Quick</option></select></Field><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={create.isPending}>{create.isPending?'Adding…':'Add website'}</button></div></form>}
  <div className="card table-wrap">{isLoading?<div className="empty">Loading websites…</div>:isError?<div className="empty">Could not load websites.</div>:!websites.length?<div className="empty"><div className="empty-icon"><Icon name="globe"/></div><strong>No websites yet</strong><div>Add your first website to start an audit.</div></div>:
  <table><thead><tr><th>Website</th><th>Environment</th><th>Security score</th><th>Status</th><th>Last scan</th><th></th></tr></thead><tbody>{websites.map(w=><tr key={w.id}><td><Link to={`/websites/${w.id}`} style={{textDecoration:'none'}}><strong>{w.name}</strong><div className="url">{w.url}</div></Link></td><td>{w.environment}</td><td><Score score={w.securityScore}/></td><td><span className={`status-pill ${w.status!=='Enabled'?'off':''}`}><span>●</span>{w.status}</span></td><td className="muted">{w.lastScanDate?new Date(w.lastScanDate).toLocaleDateString():'Never'}</td><td><div style={{display:'flex',gap:6,justifyContent:'flex-end'}}>{canWrite&&<button className="btn btn-primary" style={{minHeight:31,padding:'0 9px',fontSize:10}} onClick={()=>scan(w.id)} disabled={busy===w.id||w.status==='Disabled'}>{busy===w.id?'Scanning…':'Scan now'}</button>}{canWrite&&<button className="btn btn-secondary" style={{minHeight:31,padding:'0 9px',fontSize:10}} onClick={()=>status.mutate({id:w.id,status:w.status==='Enabled'?'Disabled':'Enabled'})}>{w.status==='Enabled'?'Disable':'Enable'}</button>}{user?.role==='Administrator'&&<button className="btn btn-danger" style={{minHeight:31,padding:'0 9px',fontSize:10}} onClick={()=>{if(confirm(`Delete ${w.name}?`))remove.mutate(w.id)}}>Delete</button>}</div></td></tr>)}</tbody></table>}</div>
 </div>
}
function Field({label,children}){return <div className="form-field"><label className="form-label">{label}</label>{children}</div>}
function Score({score}){if(score===null||score===undefined)return <span className="muted">—</span>;const cls=score<50?'bad':score<75?'warn':'';return <span className="score"><span className={`score-ring ${cls}`}>{score}</span></span>}
